<!DOCTYPE html>
<html lang="en"><head>
<script src="chapter_mlr_files/libs/clipboard/clipboard.min.js"></script>
<script src="chapter_mlr_files/libs/quarto-html/tabby.min.js"></script>
<script src="chapter_mlr_files/libs/quarto-html/popper.min.js"></script>
<script src="chapter_mlr_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="chapter_mlr_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="chapter_mlr_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="chapter_mlr_files/libs/quarto-html/quarto-syntax-highlighting-48ffa3e5b9d089919c6712c39e5b00f2.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.41">

  <meta name="author" content="고려대학교 경영대학 정지웅">
  <title>Multiple Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="chapter_mlr_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="chapter_mlr_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="chapter_mlr_files/libs/revealjs/dist/theme/quarto-8f3eebe07241f08526c91a7e9cbef8fd.css">
  <link rel="stylesheet" href="../styles/styles.css">
  <link href="chapter_mlr_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="chapter_mlr_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="chapter_mlr_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="chapter_mlr_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="chapter_mlr_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="chapter_mlr_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link href="chapter_mlr_files/libs/countdown/countdown.css" rel="stylesheet">

  <script src="chapter_mlr_files/libs/countdown/countdown.js"></script>

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Multiple Regression</h1>
  <p class="subtitle">FMB819: R을 이용한 데이터분석</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
고려대학교 경영대학 정지웅 
</div>
</div>
</div>

</section>
<section id="todays-agenda" class="slide level2">
<h2>Today’s Agenda</h2>
<ul>
<li><strong>다중 독립 변수</strong></li>
<li><strong>연속 변수와 더미 변수 해석</strong></li>
<li><strong>더미 변수 함정</strong> (Dummy Variable Trap)</li>
<li><strong>누락 변수 편향</strong> (Omitted Variable Bias)</li>
<li><strong>조정된</strong> <span class="math inline">\(R^2\)</span> (Adjusted <span class="math inline">\(R^2\)</span>)</li>
<li><strong>실증 분석:</strong>
<ul>
<li><em>학급 규모</em> (size)와 <em>학생 성취</em> (Student Performance)</li>
</ul></li>
</ul>
</section>
<section id="학급-규모와-학생-성취" class="slide level2">
<h2>학급 규모와 학생 성취</h2>
<p><strong>Angrist &amp; Lavy (1999)의 연구 분석</strong></p>
<ul>
<li>이스라엘 학생들의 성취도에 대한 <em>학급 규모</em>의 영향을 분석</li>
<li><strong>단순 선형 회귀</strong>를 사용한 경우 → 학급 규모가 커질수록 수학 및 읽기 점수가 증가하는 <strong><em>연관성</em></strong>이 발견됨</li>
</ul>
</section>
<section id="학급-규모와-학생-성취-원자료-관계" class="slide level2">
<h2>학급 규모와 학생 성취: 원자료 관계</h2>

<img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-1-1.svg" class="quarto-figure quarto-figure-center r-stretch" width="768"></section>
<section id="학급-규모와-학생-성취-단순-선형-회귀-포함" class="slide level2">
<h2>학급 규모와 학생 성취: 단순 선형 회귀 포함</h2>

<img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-2-1.svg" class="quarto-figure quarto-figure-center r-stretch" width="768"></section>
<section id="학급-규모와-학생-성취-단순-선형-회귀-포함-1" class="slide level2">
<h2>학급 규모와 학생 성취: 단순 선형 회귀 포함</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-3-1.svg" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgmath ~ classize, data = grades)
## 
## Coefficients:
## (Intercept)     classize  
##     57.7939       0.3175</code></pre>
</div>
</div>
</div></div>
</section>
<section id="학급-규모와-학생-성취-1" class="slide level2">
<h2>학급 규모와 학생 성취</h2>
<ul>
<li><p><strong>단순 선형 회귀</strong> (Simple Linear Regression) 결과에 따르면, <em>학급 규모가 학생들의 수학 및 읽기 점수와 양의 상관관계를 가짐</em> (<strong>positively associated</strong>).</p></li>
<li><p>이는 <strong>직관적으로 예상되지 않는 결과</strong>이며, <em>STAR</em> 무작위 실험 결과와도 대조적임.</p></li>
<li><p><strong>그렇다면, 학급 규모와 학생 성취 모두와 관련된 다른 변수가 있을까?</strong></p></li>
<li><p>특히, <strong>지역(location) 효과</strong>가 존재할 가능성이 있음.</p>
<ul>
<li><em>대규모 학급</em>은 부유한 대도시에서 더 흔할 수 있음.<br>
</li>
<li><em>소규모 학급</em>은 경제적으로 어려운 농촌 지역에서 더 많을 수 있음.</li>
</ul></li>
<li><p><strong>이 가설을 검증해보자.</strong></p></li>
</ul>
</section>
<section id="학급-규모와-학생-성취-교란-변수confounders" class="slide level2">
<h2>학급 규모와 학생 성취: 교란 변수(Confounders)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>학급 규모와 불리한 배경을 가진 학생 비율 간의 관계</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-5-1.svg" class="quarto-figure quarto-figure-center" width="768"></p>
</figure>
</div>
</div>
</div>
<p>➡ 평균적으로, 불리한 배경을 가진 학생 비율이 높은 학급일수록 학급 규모가 작음.</p>
</div><div class="column" style="width:50%;">
<p><strong>평균 수학 점수와 불리한 배경을 가진 학생 비율 간의 관계</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-6-1.svg" class="quarto-figure quarto-figure-center" width="768"></p>
</figure>
</div>
</div>
</div>
<p>➡ 평균적으로, 불리한 배경을 가진 학생 비율이 높을수록 평균 수학 점수가 낮아짐.</p>
</div></div>
</section>
<section id="학급-규모와-학생-성취-다중-회귀-분석" class="slide level2">
<h2>학급 규모와 학생 성취: 다중 회귀 분석</h2>
<ul>
<li><p>우리는 <strong>학급 규모가 평균 수학 점수에 미치는 효과</strong>를 알고 싶음.</p></li>
<li><p>하지만, <strong>불리한 배경을 가진 학생 비율</strong>과 학급 규모 및 평균 수학 점수 간의 <strong>음의 관계</strong>를 고려해야 함.</p></li>
<li><p>이를 위해 <strong><code>classize</code>와 <code>disadvantaged</code> 변수를 회귀 분석의 독립 변수(regressors)로 포함해야 함</strong>.</p></li>
<li><p>이렇게 하면 <strong>학급 규모가 평균 수학 점수에 미치는 효과를, 불리한 배경 변수의 영향을 제거한(purged) 형태로 추정 가능</strong>.</p></li>
</ul>
<p><strong>추정하려는 회귀 모델</strong> 다중 회귀 분석(Multiple Regression)</p>
<p><span class="math display">\[
\textrm{avg math}_i = b_0 + b_1 \text{size}_i + b_2 \text{\% disadvantaged}_i + e_i
\]</span></p>
</section>
<section id="다중-회귀-분석의-목적" class="slide level2">
<h2>다중 회귀 분석의 목적</h2>
<ul>
<li><strong>단순 선형 회귀 모델(Simple Linear Model)</strong> 은 다음과 같이 표현됨:</li>
</ul>
<p><span class="math display">\[
y_i = b_0 + b_1 x_i + e_i
\]</span></p>
<ul>
<li><p><code>X</code>가 <code>Y</code>를 <strong>인과적으로(causally) 결정한다고 주장</strong>하려면,</p>
<ul>
<li><strong><code>X</code>의 값을 변경했을 때(<code>X</code>를 조작), 다른 모든 요인은 동일하게 유지(ceteris paribus)되면서 <code>Y</code>가 변화해야 함</strong>.</li>
</ul></li>
<li><p>⚠️ 만약 <span class="math inline">\(y_i\)</span>에 영향을 주는 다른 모든 요인이 <span class="math inline">\(x_i\)</span>와 상관관계가 있다면,<br>
→ <span class="math inline">\(b_1\)</span>은 인과적 효과(Causal Effect)로 해석될 수 없음.</p></li>
<li><p>이를 해결하기 위해, <strong>모델을 확장하고(<span class="math inline">\(y_i\)</span>를 동시에 설명하는 다른 요인을 포함)</strong><br>
→ <span class="math inline">\(y_i\)</span>와 <span class="math inline">\(x_i\)</span> 모두와 관련된 변수들을 고려해야 함.</p></li>
</ul>
</section>
<section id="다중-회귀-분석-모델" class="slide level2">
<h2>다중 회귀 분석 모델</h2>
<p>확장된 회귀 모델은 다음과 같이 표현됨:</p>
<p><span class="math display">\[
y_i = b_0 + b_1 x_{1,i} + b_2 x_{2,i}  + b_3 x_{3,i} + \dots + b_k x_{k,i} + e_i
\]</span></p>
<ul>
<li>여기서 <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, …, <span class="math inline">\(x_k\)</span> 는 <span class="math inline">\(k\)</span>개의 독립 변수(regressors)<br>
</li>
<li><span class="math inline">\(b_1\)</span>, <span class="math inline">\(b_2\)</span>, …, <span class="math inline">\(b_k\)</span> 는 <strong>각 독립 변수에 대응하는 회귀 계수(coefficients)</strong></li>
</ul>
<p><strong>추정(Estimation)</strong></p>
<ul>
<li><span class="math inline">\((b_0, b_1, b_2, ..., b_k)\)</span> 값은 <strong>최소자승법(OLS, Ordinary Least Squares)</strong> 을 사용하여 추정됨.<br>
</li>
<li>즉, 다음을 <strong>최소화하는 값</strong>을 찾음:</li>
</ul>
<p><span class="math display">\[
\begin{align}
\sum_{i}{e_i^2} &amp;= \sum_{i}{(y_i - \hat{y_i})^2} \\
&amp;= \sum_{i}{[y_i - (b_0 + b_1 x_{1,i} + b_2 x_{2,i}  + b_3 x_{3,i} + \dots + b_k x_{k,i})]^2}
\end{align}
\]</span></p>
<ul>
<li><strong>OLS는 잔차 제곱합(Sum of Squared Residuals, SSR)</strong> 을 최소화하는 방식으로 최적의 계수를 찾음.</li>
</ul>
</section>
<section id="다중-회귀-분석-해석" class="slide level2">
<h2>다중 회귀 분석: 해석</h2>
<ul>
<li><p><strong>가정</strong> : 종속 변수 <span class="math inline">\((y_i)\)</span> 와 독립 변수 <span class="math inline">\((x_k)\)</span> 모두 <strong>연속형 변수(numeric variables)</strong> 라고 가정.</p></li>
<li><p><strong>절편 (</strong><span class="math inline">\(b_0\)</span>): <span class="math inline">\(x_1, x_2, x_3, ...\)</span> 모든 독립 변수가 0일 때, 예측된 <span class="math inline">\(y\)</span> 값 <span class="math inline">\(\widehat{y}\)</span></p></li>
<li><p><strong>기울기 (</strong><span class="math inline">\(b_k\)</span>): <span class="math inline">\(x_k\)</span>가 1 단위 증가할 때, <span class="math inline">\(y\)</span> 값이 평균적으로 어떻게 변하는지 예측… 단, 다른 모든 독립 변수들은 일정하게 유지!</p></li>
<li><p><strong>다른 모든 변수들을 일정하게 유지한다는 점</strong>이 <strong>단순 선형 회귀(SLM)와 다른 점</strong>.<br>
</p></li>
<li><p>즉, <span class="math inline">\(x_k\)</span>가 <span class="math inline">\(y\)</span>에 미치는 개별적인 효과를 고립시켜 분석하는 것.</p></li>
<li><p><strong>인과 추론(Causal Inference)과의 연결</strong></p>
<ul>
<li>다중 회귀 분석에서는 <strong>모델에 포함된 변수들만 일정하게 유지</strong>됨.<br>
</li>
<li>하지만, <strong>모델에 포함되지 않은 변수들은 여전히 변할 수 있어, 추정값에 편향을 일으킬 가능성이 있음.</strong></li>
</ul></li>
</ul>
</section>
<section id="r을-사용한-다중-회귀-분석" class="slide level2">
<h2><code>R</code>을 사용한 다중 회귀 분석</h2>
<ul>
<li>단순 선형 회귀와 매우 유사함.
<ul>
<li><code>lm()</code> 함수를 사용하여 다중 회귀 분석 수행 가능.</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="fu">lm</span>(<span class="at">formula =</span> dependent variable <span class="sc">~</span>  independent variable <span class="dv">1</span> <span class="sc">+</span> independent variable <span class="dv">2</span> <span class="sc">+</span> ...,</span>
<span id="cb2-2"><a href=""></a>   <span class="at">data =</span> data.frame containing the data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>학급 규모와 학생 성취: 다중 회귀 분석: <span class="math inline">\(\textrm{avg math}_i = b_0 + b_1 \textrm{size}_i + b_2 \textrm{ \% disadvantaged}_i + e_i\)</span></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgmath ~ classize + disadvantaged, data = grades)
## 
## Coefficients:
##   (Intercept)       classize  disadvantaged  
##      69.94438        0.07168       -0.33958</code></pre>
</div>
</div>
</section>
<section id="학급-규모와-학생-성취-다중-회귀-분석-1" class="slide level2 scrollable">
<h2>학급 규모와 학생 성취: 다중 회귀 분석</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgmath ~ classize + disadvantaged, data = grades)
## 
## Coefficients:
##   (Intercept)       classize  disadvantaged  
##      69.94438        0.07168       -0.33958</code></pre>
</div>
</div>
<p><strong><em>Questions</em></strong></p>
<ol type="1">
<li>각 회귀 계수(coefficients)는 어떻게 해석할 수 있는가?</li>
<li>단순 선형 회귀(SLM)와 비교했을 때 classize 계수의 변화는 어떻게 설명할 수 있는가?</li>
</ol>
</section>
<section id="학급-규모와-학생-성취-다중-회귀-분석-2" class="slide level2 scrollable">
<h2>학급 규모와 학생 성취: 다중 회귀 분석</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgmath ~ classize + disadvantaged, data = grades)
## 
## Coefficients:
##   (Intercept)       classize  disadvantaged  
##      69.94438        0.07168       -0.33958</code></pre>
</div>
</div>
<p><strong><em>Answers</em></strong></p>
<ol type="1">
<li>각 회귀 계수의 해석</li>
</ol>
<ul>
<li><p><span class="math inline">\(b_0 = 69.94\)</span>: 학급 규모 (classize) 와 불리한 배경을 가진 학생 비율 이 모두 0일 때 → 평균 수학 점수(avg math)의 예측값은 69.94</p></li>
<li><p><span class="math inline">\(b_1 = 0.07\)</span>: 불리한 배경을 가진 학생 비율을 일정하게 유지할 경우, 학급 규모가 1명 증가하면 → 평균 수학 점수가 평균적으로 0.07점 증가하는 것과 연관됨(associated).</p></li>
<li><p><span class="math inline">\(b_2 = -0.34\)</span>: 학급 규모를 일정하게 유지할 경우, 불리한 배경을 가진 학생 비율이 1% 증가하면 → 평균 수학 점수가 평균적으로 0.34점 감소하는 것과 연관됨(associated).</p></li>
</ul>
</section>
<section id="학급-규모와-학생-성취-다중-회귀-분석-3" class="slide level2 scrollable">
<h2>학급 규모와 학생 성취: 다중 회귀 분석</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgmath ~ classize + disadvantaged, data = grades)
## 
## Coefficients:
##   (Intercept)       classize  disadvantaged  
##      69.94438        0.07168       -0.33958</code></pre>
</div>
</div>
<p><strong><em>Answers</em></strong></p>
<ol start="2" type="1">
<li>단순 선형 회귀(SLM)와 비교했을 때 classize 계수의 변화는 어떻게 설명할 수 있는가?</li>
</ol>
<ul>
<li><span class="math inline">\(b_1\)</span> 값이 감소: disadvantaged 변수를 추가하자 학급 규모(size)의 계수(<span class="math inline">\(b_1\)</span>)가 감소함. 이는 예상된 결과 → 큰 학급일수록 불리한 배경을 가진 학생 비율이 작아지는 경향이 있었기 때문. 즉, 단순 선형 회귀에서는 학급 규모가 학생 성취에 미치는 “순수한 효과”뿐만 아니라, 불리한 배경을 가진 학생 비율이 적은 영향도 포함하고 있었음.</li>
</ul>
</section>
<section id="task-1" class="slide level2 scrollable" data-background-color="#ffebf0">
<h2>Task 1</h2>
<div style="position: absolute; top: -30px; right: 10px; font-size: 0.8em;">
<p></p><div class="countdown" id="timer_bd88a406" data-update-every="1" tabindex="0" style="top:0;right:0;"> <div class="countdown-controls"><button class="countdown-bump-down">−</button><button class="countdown-bump-up">+</button></div> <code class="countdown-time"><span class="countdown-digits minutes">10</span><span class="countdown-digits colon">:</span><span class="countdown-digits seconds">00</span></code> </div><p></p>
</div>
<ul>
<li><strong>읽기(Reading) 점수를 종속 변수(Dependent Variable)</strong> 로 설정하여 회귀 분석을 수행</li>
</ul>
<ol type="1">
<li><code>haven</code> 패키지의 <code>read_dta()</code> 함수를 사용하여 데이터를 불러오기. 데이터를 <code>grades</code>라는 객체에 저장</li>
</ol>
<ol start="2" type="1">
<li>avgverb (읽기 점수)를 종속 변수로, classize와 disadvantaged를 독립 변수로 사용하여 회귀분석. 결과를 reg 객체에 저장. 각 계수(coefficient)의 의미는 무엇인가? 단순 선형 회귀(Simple Linear Regression)와 비교했을 때 계수는 어떻게 달라졌는가? 수학 점수 회귀 분석(Math Score Regression)과 비교했을 때 계수의 차이점은 무엇인가?</li>
</ol>
<p>(Optional) 데이터셋에서 추가 가능한 변수를 확인하고 회귀 분석을 확장하시오. 모든 변수를 포함한 회귀 분석을 수행하고 reg_full 객체에 저장.</p>
<ul>
<li>추가된 변수들의 계수(sign &amp; magnitude)를 해석하시오.</li>
<li>추가된 변수가 포함됨으로 인해 classize 및 disadvantaged의 계수는 어떻게 변했는가?</li>
<li>전체 모델의 설명력이 증가했는가? (<span class="math inline">\(R^2\)</span> 값 확인)</li>
</ul>
</section>
<section id="연속형-변수와-더미-변수의-회귀-계수-해석" class="slide level2">
<h2>연속형 변수와 더미 변수의 회귀 계수 해석</h2>
<ul>
<li><p>연속형(numeric, continuous) 변수의 계수 해석 방법은 이미 알고 있음.</p></li>
<li><p>그렇다면, 독립 변수 중 하나가 <strong><em>더미 변수(dummy variable)</em></strong> 라면?</p></li>
</ul>
<p><em>예)</em>: 아래 회귀 모델에서 각 계수의 의미는?</p>
<p><span class="math display">\[
\text{avg math}_i = b_0 + b_1\text{size}_i + b_2\text{religious}_i +e_i
\]</span></p>
<ul>
<li><code>religious</code>: <strong>1이면</strong> 해당 학교가 <em>종교 학교</em>, <strong>0이면</strong> 해당 학교가 <em>일반 학교</em></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgmath ~ classize + religious, data = grades)
## 
## Coefficients:
## (Intercept)     classize    religious  
##     61.3092       0.2311      -3.7800</code></pre>
</div>
</div>
</section>
<section id="연속형-변수와-더미-변수를-포함한-회귀-분석" class="slide level2">
<h2>연속형 변수와 더미 변수를 포함한 회귀 분석</h2>
<p><span class="math display">\[
\text{avg math}_i = \color{#d96502}{b_0} + \color{#d90502}{b_1}\text{size}_i + \color{#027D83}{b_2}\text{religious}_i +e_i
\]</span></p>
<ul>
<li>다음이 성립</li>
</ul>
<p><span class="math display">\[\begin{align}
\mathbb{E}(\text{avg math} | \text{religious} = 0 \text{ &amp; } \text{size} = 0) &amp;= \color{#d96502}{b_0} + \color{#d90502}{b_1} \times 0 + \color{#027D83}{b_2} \times 0 \\
&amp;= \color{#d96502}{b_0}
\end{align}\]</span></p>
<p><strong>절편 (<span class="math inline">\(b_0\)</span>)</strong>: <code>religious = 0</code> (일반 학교)이고, <code>size = 0</code>인 경우의 <strong>예측된 평균 수학 점수</strong></p>
<ul>
<li><span class="math inline">\(\color{#d96502}{b_0}\)</span> 는 학급 규모가 0이고, 학교가 일반 학교일 때의 평균 수학 점수를 의미.</li>
</ul>
</section>
<section id="연속형-변수와-더미-변수를-포함한-회귀-분석-1" class="slide level2">
<h2>연속형 변수와 더미 변수를 포함한 회귀 분석</h2>
<p><span class="math display">\[
\text{avg math}_i = \color{#d96502}{b_0} + \color{#d90502}{b_1}\text{size}_i + \color{#027D83}{b_2}\text{religious}_i +e_i
\]</span></p>
<ul>
<li>또한 다음이 성립</li>
</ul>
<p><span class="math display">\[\begin{equation}
\mathbb{E}(\text{avg math} | \text{religious} \in \{0,1\} \text{ &amp; } \color{#d90502}{\text{size} = n_1}) = \color{#d96502}{b_0} + \color{#d90502}{b_1} \times n_1 + \color{#027D83}{b_2} \times \text{religious}
\end{equation}\]</span> <span class="math display">\[\begin{multline}
\mathbb{E}(\text{avg math} | \text{religious} \in \{0,1\} \text{ &amp; } \color{#d90502}{\text{size} = n_1+1}) = \\ \color{#d96502}{b_0} + \color{#d90502}{b_1} \times (n_1+1) + \color{#027D83}{b_2} \times \text{religious}
\end{multline}\]</span> <span class="math display">\[\begin{multline}
\mathbb{E}(\text{avg math} | \text{religious} \in \{0,1\} \text{ &amp; } \color{#d90502}{\text{size} = n_1+1}) - \\ \mathbb{E}(\text{avg math} | \text{religious} \in \{0,1\} \text{ &amp; } \color{#d90502}{\text{size} = n_1}) \\
= \color{#d96502}{b_0} + \color{#d90502}{b_1} \times (n_1+1) + \color{#027D83}{b_2} \times \text{religious} - (\color{#d96502}{b_0} + \color{#d90502}{b_1} \times n_1 + \color{#027D83}{b_2} \times \text{religious}) = \color{#d90502}{b_1}
\end{multline}\]</span></p>
<ul>
<li><span class="math inline">\(\color{#d90502}{b_1}\)</span>은 학급 규모(size)가 1명 증가할 때, 평균 수학 점수가 평균적으로 변화하는 정도를 나타냄. 단, <strong>학교의 종교적 특성(<code>religious</code> 변수)은 일정하게 유지된 상태에서</strong></li>
</ul>
</section>
<section id="연속형-변수와-더미-변수를-포함한-회귀-분석-2" class="slide level2">
<h2>연속형 변수와 더미 변수를 포함한 회귀 분석</h2>
<p><span class="math display">\[
\text{avg math}_i = \color{#d96502}{b_0} + \color{#d90502}{b_1}\text{size}_i + \color{#027D83}{b_2}\text{religious}_i +e_i
\]</span></p>
<ul>
<li>그리고 다음이 성립</li>
</ul>
<p><span class="math display">\[\begin{align}
\mathbb{E}(\text{avg math} | \color{#027D83}{\text{religious} = 1} \text{ &amp; } \text{size} \in \mathbb{N}) &amp;= \color{#d96502}{b_0} + \color{#d90502}{b_1} \times \text{size} + \color{#027D83}{b_2} \times 1 \\
&amp;= \color{#d96502}{b_0} + \color{#d90502}{b_1} \times \text{size} + \color{#027D83}{b_2}
\end{align}\]</span> <span class="math display">\[\begin{align}
\mathbb{E}(\text{avg math} | \color{#027D83}{\text{religious} = 0} \text{ &amp; } \text{size} \in \mathbb{N}) &amp;= \color{#d96502}{b_0} + \color{#d90502}{b_1} \times \text{size} + \color{#027D83}{b_2} \times 0 \\
&amp;= \color{#d96502}{b_0} + \color{#d90502}{b_1} \times \text{size}
\end{align}\]</span> <span class="math display">\[\begin{multline}
\mathbb{E}(\text{avg math} | \color{#027D83}{\text{religious} = 1} \text{ &amp; } \text{size} \in \mathbb{N}) - \\ \mathbb{E}(\text{avg math} | \color{#027D83}{\text{religious} =0} \text{ &amp; } \text{size} \in \mathbb{N}) \\
= \color{#d96502}{b_0} + \color{#d90502}{b_1} \times \text{size} + \color{#027D83}{b_2}- (\color{#d96502}{b_0} + \color{#d90502}{b_1} \times \text{size}) = \color{#027D83}{b_2}
\end{multline}\]</span></p>
<p><span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(\color{#027D83}{b_2}\)</span>는 학급 규모를 일정하게 유지한 상태에서 <strong>종교계 학교와 비종교계 학교 간 평균 수학 점수의 기대 차이</strong>를 의미</p>
</section>
<section id="연속형-변수와-더미-변수를-포함한-회귀-분석-요약" class="slide level2">
<h2>연속형 변수와 더미 변수를 포함한 회귀 분석: 요약</h2>
<p><span class="math display">\[
\text{avg math}_i = \color{#d96502}{b_0} + \color{#d90502}{b_1}\text{size}_i + \color{#027D83}{b_2}\text{religious}_i +e_i
\]</span></p>
<p><span class="math display">\[\begin{equation}
\color{#d96502}{b_0} = \mathbb{E}(\text{avg math} | \text{religious} = 0 \text{ &amp; } \text{size} = 0)
\end{equation}\]</span> <span class="math display">\[\begin{multline}
\color{#d90502}{b_1} = \mathbb{E}(\text{avg math} | \text{religious} \in \{0,1\} \text{ &amp; } \color{#d90502}{\text{size} = n_1+1}) - \\ \mathbb{E}(\text{avg math} | \text{religious} \in \{0,1\} \text{ &amp; } \color{#d90502}{\text{size} = n_1})
\end{multline}\]</span> <span class="math display">\[\begin{multline}
\color{#027D83}{b_2} = \mathbb{E}(\text{avg math} | \color{#027D83}{\text{religious} = 1} \text{ &amp; } \text{size} \in \mathbb{N}) - \\ \mathbb{E}(\text{avg math} | \color{#027D83}{\text{religious} =0} \text{ &amp; } \text{size} \in \mathbb{N})
\end{multline}\]</span> <span class="math display">\[\begin{equation}
\color{#d96502}{b_0} + \color{#027D83}{b_2} = \mathbb{E}(\text{avg math} | \text{religious} = 1 \text{ &amp; } \text{size} = 0)
\end{equation}\]</span></p>
</section>
<section id="연속형-변수와-더미-변수를-포함한-회귀-분석-시각화" class="slide level2">
<h2>연속형 변수와 더미 변수를 포함한 회귀 분석: 시각화</h2>
<p><span class="math display">\[
\text{avg math}_i = \color{#d96502}{b_0} + \color{#d90502}{b_1}\text{size}_i + \color{#027D83}{b_2}\text{religious}_i +e_i
\]</span></p>

<img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-16-1.svg" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="연속형-변수와-더미-변수를-포함한-회귀-분석-시각화-1" class="slide level2">
<h2>연속형 변수와 더미 변수를 포함한 회귀 분석: 시각화</h2>
<p><span class="math display">\[
\text{avg math}_i = \color{#d96502}{b_0} + \color{#d90502}{b_1}\text{size}_i + \color{#027D83}{b_2}\text{religious}_i +e_i
\]</span></p>

<img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-17-1.svg" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="연속형-변수와-더미-변수를-포함한-회귀-분석-시각화-2" class="slide level2">
<h2>연속형 변수와 더미 변수를 포함한 회귀 분석: 시각화</h2>
<p><span class="math display">\[
\text{avg math}_i = \color{#d96502}{b_0} + \color{#d90502}{b_1}\text{size}_i + \color{#027D83}{b_2}\text{religious}_i +e_i
\]</span></p>

<img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-18-1.svg" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="연속형-변수와-더미-변수를-포함한-회귀-분석-시각화-3" class="slide level2">
<h2>연속형 변수와 더미 변수를 포함한 회귀 분석: 시각화</h2>
<p><span class="math display">\[
\text{avg math}_i = \color{#d96502}{b_0} + \color{#d90502}{b_1}\text{size}_i + \color{#027D83}{b_2}\text{religious}_i +e_i
\]</span></p>

<img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-19-1.svg" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="연속형-변수와-더미-변수를-포함한-회귀-분석-시각화-4" class="slide level2">
<h2>연속형 변수와 더미 변수를 포함한 회귀 분석: 시각화</h2>
<p><span class="math display">\[
\text{avg math}_i = \color{#d96502}{b_0} + \color{#d90502}{b_1}\text{size}_i + \color{#027D83}{b_2}\text{religious}_i +e_i
\]</span></p>

<img data-src="chapter_mlr_files/figure-revealjs/unnamed-chunk-20-1.svg" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="완전-다중공선성perfect-collinearity" class="slide level2">
<h2>완전 다중공선성(Perfect Collinearity)</h2>
<ul>
<li>추가하는 변수는 반드시 <strong>새로운 정보</strong>를 제공해야 함.</li>
<li>회귀 모형에 추가하는 변수들은 <strong>완전히 선형결합(linear combination)</strong>이 될 수 없음.</li>
</ul>
<p><span class="math display">\[
x_2 \neq ax_1 + b
\]</span></p>
<ul>
<li><p>즉, 하나의 독립 변수를 다른 독립 변수들의 조합으로 완전히 표현할 수 있으면 안 됨.</p></li>
<li><p><strong>완벽하게 선형 결합된 경우</strong> → 회귀 분석 수행 불가능</p></li>
<li><p><strong>높은 상관관계를 가지는 경우</strong>: <strong>각 독립 변수의 개별적 효과(계수)를 정확히 분리하기 어려움</strong> → 추정된 계수의 신뢰도가 낮아질 수 있음</p></li>
<li><p><strong>관측치 수(Observations) &gt; 독립 변수 개수(Independent Variables)</strong>: <strong>즉, 너무 많은 변수를 추가하면 과적합(overfitting) 문제가 발생할 수 있음.</strong> → ✅ <strong>반드시 충족해야 하는 조건!</strong></p></li>
</ul>
</section>
<section id="완전-다중공선성과-더미-변수-함정-dummy-variable-trap" class="slide level2">
<h2>완전 다중공선성과 더미 변수 함정 (Dummy Variable Trap)</h2>
<ul>
<li><p><strong>범주형 변수(categorical variables)</strong>란, 특정 개수의 <strong>“레벨(levels)”</strong>을 가지는 변수 (예: 성별, 계절, 인종, 교육 수준 등)</p></li>
<li><p><strong>🏫 <code>religious</code> 변수 예제</strong>: <code>religious</code> 변수를 포함한 회귀 분석 수행</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgmath ~ classize + religious, data = grades)
## 
## Coefficients:
## (Intercept)     classize    religious  
##     61.3092       0.2311      -3.7800</code></pre>
</div>
</div>
<p>⚠ 더미 변수 함정: 만약 religious 변수를 두 개의 더미 변수(is_religious, is_notreligious)로 변환하여 사용한다면?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>grades <span class="ot">&lt;-</span> grades <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">is_religious =</span> (religious <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb9-3"><a href=""></a>         <span class="at">is_notreligious =</span> (religious <span class="sc">==</span> <span class="dv">0</span>))</span>
<span id="cb9-4"><a href=""></a></span>
<span id="cb9-5"><a href=""></a><span class="fu">lm</span>(avgmath <span class="sc">~</span> classize <span class="sc">+</span> is_religious <span class="sc">+</span> is_notreligious, grades)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgmath ~ classize + is_religious + is_notreligious, 
##     data = grades)
## 
## Coefficients:
##         (Intercept)             classize     is_religiousTRUE  
##             61.3092               0.2311              -3.7800  
## is_notreligiousTRUE  
##                  NA</code></pre>
</div>
</div>
<p>❓ 왜 하나의 계수만 추정되는가? 완전 다중공선성 발생 → is_religious와 is_notreligious는 항상 1의 합을 가짐. 즉, 한 변수를 다른 변수로 완전히 설명 가능</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a>grades <span class="sc">%&gt;%</span> <span class="fu">count</span>(is_religious <span class="sc">==</span> <span class="dv">1</span> <span class="sc">-</span> is_notreligious)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 1 × 2
##   `is_religious == 1 - is_notreligious`     n
##   &lt;lgl&gt;                                 &lt;int&gt;
## 1 TRUE                                   2019</code></pre>
</div>
</div>
</div></div>
</section>
<section id="완전-다중공선성과-더미-변수-함정-dummy-variable-trap-1" class="slide level2">
<h2>완전 다중공선성과 더미 변수 함정 (Dummy Variable Trap)</h2>
<p><code>R</code>은 <strong>완전 다중공선성(perfect collinearity)</strong>을 자동으로 감지하고, <strong>한 변수를 자동으로 제거(drop)</strong> 함.</p>
<p><strong>⚠ 기준(reference) 그룹과 계수 해석</strong></p>
<ul>
<li>✅ 제거된 변수(omitted category)는 기준 그룹(reference group)이 됨!<br>
</li>
<li>💡 모든 계수는 이 <strong>기준 그룹 대비 변화량</strong>을 의미함.</li>
</ul>
<p><span class="math display">\[\begin{multline}
\color{#027D83}{b_2} = \mathbb{E}(\text{avg math} | \color{#027D83}{\text{religious} = 1} \text{ &amp; } \text{size} \in \mathbb{N}) - \\  
\mathbb{E}(\text{avg math} | \color{#027D83}{\text{religious} =0} \text{ &amp; } \text{size} \in \mathbb{N})
\end{multline}\]</span></p>
<ul>
<li>즉, <span class="math inline">\(b_2\)</span>는 종교 학교(<code>religious = 1</code>)와 일반 학교(<code>religious = 0</code>) 간의 평균 수학 점수 차이를 나타냄.</li>
</ul>
<p><strong>📌 두 개 이상의 범주(category)가 있는 경우</strong></p>
<ul>
<li><strong>카테고리가 2개 이상</strong>인 경우, 모든 카테고리에 대해 더미 변수를 만들 필요 없음.<br>
</li>
<li><code>R</code>은 <code>character</code> 또는 <code>factor</code> 형식의 변수들을 자동으로 감지하고, <strong>적절한 더미 변수를 생성</strong>함.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>grades <span class="ot">&lt;-</span> grades <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">religious =</span> <span class="fu">factor</span>(religious)) <span class="co"># 범주형 변수로 변환</span></span>
<span id="cb13-3"><a href=""></a></span>
<span id="cb13-4"><a href=""></a><span class="fu">lm</span>(avgmath <span class="sc">~</span> classize <span class="sc">+</span> religious, grades) <span class="co"># 자동으로 한 변수 제외</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgmath ~ classize + religious, data = grades)
## 
## Coefficients:
## (Intercept)     classize   religious1  
##     61.3092       0.2311      -3.7800</code></pre>
</div>
</div>
</section>
<section id="task-2" class="slide level2 scrollable" data-background-color="#ffebf0">
<h2>Task 2</h2>
<div style="position: absolute; top: -30px; right: 10px; font-size: 0.8em;">
<p></p><div class="countdown" id="timer_6ab0d6d4" data-update-every="1" tabindex="0" style="top:0;right:0;"> <div class="countdown-controls"><button class="countdown-bump-down">−</button><button class="countdown-bump-up">+</button></div> <code class="countdown-time"><span class="countdown-digits minutes">10</span><span class="countdown-digits colon">:</span><span class="countdown-digits seconds">00</span></code> </div><p></p>
</div>
<ol type="1">
<li><strong>STAR 데이터</strong>를 다운로드 <a href="https://chung-jiwoong.github.io/FMB819-Slides/chapter_causality/data/star_data.csv">링크</a>. <code>read.csv()</code>를 사용하여 <code>star_df</code> 객체에 저장. <code>NA</code> 값이 있는 행을 제거: <code>star_df &lt;- star_df[complete.cases(star_df),]</code></li>
</ol>
<ol start="2" type="1">
<li>세 개의 더미 변수를 생성 (<em>힌트</em>: <code>dummy = (variable=="value")</code>):</li>
</ol>
<ul>
<li><code>small</code>: 학생이 소규모 학급에 배정되었으면 TRUE, 아니면 FALSE</li>
<li><code>regular</code>: 학생이 일반 학급에 배정되었으면 TRUE, 아니면 FALSE</li>
<li><code>regular_plus</code>: 학생이 보조 교사가 있는 일반 학급에 배정되었으면 TRUE, 아니면 FALSE</li>
<li>또한, sum 변수를 만들어 위 세 개 변수의 합을 확인. 무엇을 뜻하는가?</li>
</ul>
<ol start="3" type="1">
<li><p><code>math</code>를 <code>regular_plus</code>로 회귀 분석. regular+aide 반에 있는 학생의 평균 <code>math</code> 점수는?</p></li>
<li><p><code>math</code>를 <code>small</code>, <code>regular</code>, <code>regular_plus</code>로 회귀 분석. 어느 범주가 사라졌나?</p></li>
<li><p><code>math</code>를 <code>star</code> 변수로 회귀 분석. 어느 범주가 사라졌나? 계수를 해석하시오.</p></li>
</ol>
</section>
<section id="누락변수-편의-omitted-variable-bias-ovb" class="slide level2">
<h2>누락변수 편의 (Omitted Variable Bias, OVB)</h2>
<ul>
<li><p><strong><em>OVB</em></strong> 이란, 회귀 분석에서 중요한 <strong>통제 변수(control variable)</strong> 를 제외함으로써 발생하는 <strong>편의(bias)</strong> 을 의미.</p></li>
<li><p>이로 인해 관심 있는 독립 변수의 계수를 <strong>신뢰할 수 없고(biased), 왜곡될 수 있음.</strong></p></li>
</ul>
<p><span class="math inline">\(y\)</span>: 종속변수, <span class="math inline">\(x\)</span>: 독립변수, <span class="math inline">\(z\)</span>: 누락변수인 경우 다음 회귀분석이 가능</p>
<p><strong>1️⃣ 단순 선형 회귀 모델 (Simple Linear Model)</strong></p>
<p><span class="math display">\[
y = b_0 + b_1x + e
\]</span></p>
<ul>
<li>이 경우, <span class="math inline">\(x\)</span>와 <span class="math inline">\(z\)</span>가 동시에 <span class="math inline">\(y\)</span>에 영향을 미친다면, <span class="math inline">\(z\)</span>를 제외하면 <span class="math inline">\(b_1\)</span>이 편향될 수 있음.</li>
</ul>
<p><strong>2️⃣ 다중 선형 회귀 모델 (Multiple Linear Model)</strong>: 만약 <span class="math inline">\(z\)</span> 변수를 포함한다면?</p>
<p><span class="math display">\[
y = c_0 + c_1x + \color{#d90502}{c_2}z + e
\]</span></p>
<ul>
<li>이 모델에서는 <span class="math inline">\(x\)</span>뿐만 아니라 누락된 변수 <span class="math inline">\(z\)</span>도 <span class="math inline">\(y\)</span>에 영향을 미침. 즉, <span class="math inline">\(z\)</span>를 포함하면, <span class="math inline">\(c_1\)</span>이 더 정확한 값을 가질 수 있음.</li>
</ul>
</section>
<section id="누락변수-편의-omitted-variable-bias-ovb-1" class="slide level2">
<h2>누락변수 편의 (Omitted Variable Bias, OVB)</h2>
<p><strong>3️⃣ 누락된 변수와</strong> <span class="math inline">\(x\)</span>의 관계 (Omitted Variable on Regressor)</p>
<p><span class="math display">\[
z = d_0 + \color{#d96502}{d_1}x + e
\]</span></p>
<ul>
<li>이 모델은 <span class="math inline">\(x\)</span>와 생략된 변수 <span class="math inline">\(z\)</span>가 서로 상관관계가 있을 경우를 나타냄.</li>
<li>즉, <span class="math inline">\(x\)</span>가 <span class="math inline">\(z\)</span>에 영향을 미친다면, 단순 회귀 분석에서 <span class="math inline">\(b_1\)</span>의 추정치는 신뢰할 수 없게 됨.</li>
</ul>
<p><strong>📌 OVB 공식</strong></p>
<p><span class="math display">\[
\text{OVB} = \color{#d90502}{c_2} \times \color{#d96502}{d_1}
\]</span></p>
<p>즉,</p>
<p><span class="math display">\[
b_1 = c_1 + OVB
\]</span></p>
<p>💡 <strong>결론:</strong><br>
만약 <span class="math inline">\(z\)</span>를 생략하면, <span class="math inline">\(b_1\)</span>은 <span class="math inline">\(c_1\)</span>에 OVB가 더해진 값이 되어, 실제 값과 차이가 날 수 있음.</p>
</section>
<section id="누락변수-편의-omitted-variable-bias-ovb-2" class="slide level2 scrollable">
<h2>누락변수 편의 (Omitted Variable Bias, OVB)</h2>
<p><span class="math display">\[
\text{OVB} = \underbrace{\text{다중 회귀에서 생략된 변수의 계수}}_{\color{#d90502}{c_2}} \times \underbrace{\frac{Cov(x,z)}{Var(x)}}_{\color{#d96502}{d_1}}
\]</span></p>
<p><strong>OVB의 의미</strong></p>
<ol type="1">
<li>OVB의 크기(magnitude)
<ul>
<li><span class="math inline">\(z\)</span> 변수가 관측되는 경우, OVB의 크기를 직접 계산할 수 있음.</li>
</ul></li>
<li>OVB의 부호(sign) (양수/음수 여부)
<ul>
<li>현실적으로는 <span class="math inline">\(z\)</span> 변수를 관측할 수 없는 경우가 많기 때문에, <strong>OVB의 부호가 더 중요한 분석 요소</strong>가 됨.</li>
<li>OVB가 <strong>양수(+)인지 음수(-)인지</strong>를 판단하면, <span class="math inline">\(x\)</span>의 계수가 과대(+) 또는 과소(-) 추정되는지 예측할 수 있음.</li>
</ul></li>
</ol>
<div class="callout callout-none no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>소득(income)과 교육연수(years of education) 사이의 관계를 분석할 때,</p>
<ol type="1">
<li>단순 회귀 분석에서 소득을 교육연수에 회귀(regression) 시키면 신뢰할 수 없는 추정치가 나올 가능성이 있다. 왜 그럴까?</li>
<li>어떤 변수가 누락된 변수(omitted variable)일 수 있을까?<br>
</li>
<li>OVB의 부호(+) 또는 (-)는 어떻게 예상할 수 있을까?</li>
</ol>
</div>
</div>
</div>
</section>
<section id="누락변수-편의-omitted-variable-bias-ovb-예제" class="slide level2">
<h2>누락변수 편의 (Omitted Variable Bias, OVB): 예제</h2>
<ul>
<li>학급 규모(<code>classize</code>)가 학생들의 평균 수학 점수(<code>avgmath</code>)에 미치는 영향</li>
</ul>
<p><span class="math display">\[
\text{avg math} = b_0 + b_1\text{size} + e
\]</span></p>
<p><strong><em>단순회귀모형:</em></strong> <span class="math inline">\(\text{avg math} = b_0 + b_1\text{size} + e\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## (Intercept)    classize 
##  57.7939158   0.3174906</code></pre>
</div>
</div>
<p><strong><em>다중회귀모형:</em></strong> <span class="math inline">\(\text{avg math} = c_0 + c_1\text{size} + \color{#d90502}{c_2}\text{ \% disadvantaged} + e\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>##   (Intercept)      classize disadvantaged 
##   69.94438332    0.07167819   -0.33957877</code></pre>
</div>
</div>
<p><strong><em>누락변수와 독립변수</em></strong>: <span class="math inline">\(\text{\% disadvantaged} = d_0 + \color{#d96502}{d_1}\text{size} + e\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>## (Intercept)    classize 
##  35.7809990  -0.7238744</code></pre>
</div>
</div>
<p>따라서: <span class="math display">\[b_1 = 0.317 = \underbrace{0.072}_{c_1} + \underbrace{(-0.34)}_{\color{#d90502}{c_2}} \times \underbrace{(-0.724)}_{\color{#d96502}{d_1}} = c_1 + OVB\]</span></p>
</section>
<section id="수정된-결정-계수-adjusted-r2" class="slide level2">
<h2>수정된 결정 계수 (Adjusted <span class="math inline">\(R^2\)</span>)</h2>
<ul>
<li><p><span class="math inline">\(R^2\)</span> (결정 계수) 는 회귀 모델이 <strong>종속 변수(</strong><span class="math inline">\(y\)</span>)의 변동을 얼마나 설명하는지 나타내는 지표.</p></li>
<li><p>하지만, <strong>새로운 변수를 추가할 때마다</strong> <span class="math inline">\(R^2\)</span> 값은 항상 증가.</p>
<ul>
<li>심지어 <strong>의미 없는 변수라도 추가하면</strong> <span class="math inline">\(R^2\)</span>이 증가할 수 있음!</li>
</ul></li>
<li><p>이를 보완하기 위해 <strong>수정된</strong> <span class="math inline">\(R^2\)</span> (Adjusted <span class="math inline">\(R^2\)</span>) 개념이 도입</p>
<ul>
<li><strong>불필요한 변수를 추가하는 것을 방지하기 위해 패널티(penalty)를 부과</strong><br>
</li>
<li>하지만, 대부분의 경우 <span class="math inline">\(R^2\)</span>와 수정된 <span class="math inline">\(R^2\)</span>는 큰 차이가 없음</li>
</ul></li>
</ul>
</section>
<section id="task-3" class="slide level2 scrollable" data-background-color="#ffebf0">
<h2>Task 3</h2>
<div style="position: absolute; top: -30px; right: 10px; font-size: 0.8em;">
<p></p><div class="countdown" id="timer_54f3fc50" data-update-every="1" tabindex="0" style="top:0;right:0;"> <div class="countdown-controls"><button class="countdown-bump-down">−</button><button class="countdown-bump-up">+</button></div> <code class="countdown-time"><span class="countdown-digits minutes">10</span><span class="countdown-digits colon">:</span><span class="countdown-digits seconds">00</span></code> </div><p></p>
</div>
<ol type="1">
<li><p>Task 2에서 필터링한 <em>STAR</em> 데이터를 사용하여 <code>math</code>를 <code>school</code> 변수에 대해 회귀 분석하시오. <code>school</code> 변수가 포함하는 값들을 먼저 확인. 회귀 계수를 해석하시오. 누락된 범주 (category)는? 결과가 예상과 일치하는가? 만약 다르다면 왜 그런가? 누락된 변수가 존재할 가능성이 있는가?</p></li>
<li><p><code>lunch</code> 변수가 <code>"free"</code>인 학생들의 비율을 <strong>학교 위치(school) 별로 계산</strong>하시오. 결과를 보고, <strong>무료 점심 자격 여부(<code>free</code>) 변수를 추가하여 이전 회귀 분석을 다시 수행</strong>하시오. <code>free</code> 변수를 추가했을 때 회귀 계수는 어떻게 변화하는가?</p></li>
<li><p><code>math</code>를 <code>star</code> 변수에 대해 회귀 분석하시오. 다음의 모든 변수를 포함하여 다중 회귀 분석을 수행하시오:<br>
<code>math ~ star + gender + ethnicity + lunch + degree + experience + school</code>. 무작위 실험이 <strong>잘 수행되었다고 판단할 수 있는가?</strong></p></li>
<li><p><strong>다중 회귀 분석</strong>에서 얻은 <strong>수정된</strong> <span class="math inline">\(R^2\)</span> 값을 확인하시오. 수정된 <span class="math inline">\(R^2\)</span> 값이 의미하는 바는 무엇인가? 관측 가능한 개별 학생, 교사, 학교 특성이 학업 성취도에 미치는 중요성에 대해 어떤 결론을 내릴 수 있는가?</p></li>
<li><p>(Optional) <code>math</code>를 <code>gender</code>와 <code>experience</code> 변수에 대해 회귀 분석하시오. 회귀 계수를 어떻게 해석할 수 있는가? 이러한 회귀 분석 결과를 시각적으로 표현한다면 어떻게 보일 것인가?</p></li>
</ol>
</section>
<section id="인과-관계를-찾아가는-길" class="slide level2">
<h2>🔍 인과 관계를 찾아가는 길</h2>
<p>✅ <strong><em>데이터를 어떻게 다룰까?</em></strong> : 읽기(Read), 정리(Tidy), 시각화(Visualize)…</p>
<p>🚧 <strong><em>변수간 관계를 어떻게 요약할까?</em></strong> …단순 / 다중 선형 회귀…계속 학습</p>
<p>✅ 인과 관계(Causality)란 무엇인가?</p>
<p>❌ 전체 모집단을 관측하지 못하면 어떻게 할까?</p>
<p>❌ 우리의 연구 결과가 단순한 무작위(Randomness) 때문일 수도 있을까?</p>
<p>❌ 실제로 외생성을 어떻게 찾아낼 수 있을까?</p>
</section>
<section class="slide level2">

<p><link href="https://fonts.googleapis.com/css2?family=Pacifico&amp;display=swap" rel="stylesheet"></p>
<div style="display: flex; justify-content: center; align-items: center; height: 70vh;">
<h2 style="color: #ff6666; text-align: center; font-family: 'Pacifico', cursive; font-size: 50px;">
<p>THE END!</p>
</h2>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="chapter_mlr_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="chapter_mlr_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="chapter_mlr_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="chapter_mlr_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="chapter_mlr_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="chapter_mlr_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="chapter_mlr_files/libs/revealjs/plugin/reveal-text-resizer/revealjs-text-resizer.js"></script>
  <script src="chapter_mlr_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="chapter_mlr_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="chapter_mlr_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="chapter_mlr_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="chapter_mlr_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, RevealTextResizer, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>