<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.41">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Multiple Linear Regressionn</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="mlr_solution_files/libs/clipboard/clipboard.min.js"></script>
<script src="mlr_solution_files/libs/quarto-html/quarto.js"></script>
<script src="mlr_solution_files/libs/quarto-html/popper.min.js"></script>
<script src="mlr_solution_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="mlr_solution_files/libs/quarto-html/anchor.min.js"></script>
<link href="mlr_solution_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="mlr_solution_files/libs/quarto-html/quarto-syntax-highlighting-48ffa3e5b9d089919c6712c39e5b00f2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="mlr_solution_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="mlr_solution_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="mlr_solution_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multiple Linear Regressionn</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="task-1" class="level2">
<h2 class="anchored" data-anchor-id="task-1">Task 1</h2>
<ul>
<li><strong>읽기(Reading) 점수를 종속 변수(Dependent Variable)</strong> 로 설정하여 회귀 분석을 수행</li>
</ul>
<ol type="1">
<li><code>haven</code> 패키지의 <code>read_dta()</code> 함수를 사용하여 데이터를 불러오기. 데이터를 <code>grades</code>라는 객체에 저장</li>
</ol>
<ol start="2" type="1">
<li>avgverb (읽기 점수)를 종속 변수로, classize와 disadvantaged를 독립 변수로 사용하여 회귀분석. 결과를 reg 객체에 저장. 각 계수(coefficient)의 의미는 무엇인가? 단순 선형 회귀(Simple Linear Regression)와 비교했을 때 계수는 어떻게 달라졌는가? 수학 점수 회귀 분석(Math Score Regression)과 비교했을 때 계수의 차이점은 무엇인가?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(avgverb <span class="sc">~</span> classize <span class="sc">+</span> disadvantaged, grades)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>reg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgverb ~ classize + disadvantaged, data = grades)
## 
## Coefficients:
##   (Intercept)       classize  disadvantaged  
##      80.23878       -0.03083       -0.34967</code></pre>
</div>
</div>
<p><strong>절편(intercept)은 학급 크기(class size)와 저소득 학생 비율이 0일 때의 예상 읽기 점수이며, 그 값은 80입니다. 수업에서 논의했듯이, 현실에서는 학생이 없으면 시험 점수도 존재할 수 없기 때문에 이 값은 의미가 없습니다. 학급 규모에 대한 계수는 -0.03으로, 저소득 학생 비율을 통제할 때 학급에 학생 1명이 추가되면 평균 읽기 점수가 0.03점 감소한다는 뜻입니다. 이는 수학 점수를 종속 변수로 했을 때 양의 값을 보였던 것과 반대이며, 읽기 점수가 0에서 100까지인 점을 고려할 때 매우 작은 효과입니다. 저소득 학생 비율(disadvantaged)의 계수는 -0.35로, 학급 크기를 고정하면 저소득 학생 비율이 1%p 증가할 때 평균 읽기 점수는 0.35점 감소한다는 뜻입니다. 이는 수학 점수 분석 결과와 유사한 크기이며, 10%p 증가 시에도 점수는 3.5점 정도만 감소합니다.</strong></p>
<p>(Optional) 데이터셋에서 추가 가능한 변수를 확인하고 회귀 분석을 확장하시오. 모든 변수를 포함한 회귀 분석을 수행하고 reg_full 객체에 저장.</p>
<ul>
<li>추가된 변수들의 계수(sign &amp; magnitude)를 해석하시오.</li>
<li>추가된 변수가 포함됨으로 인해 classize 및 disadvantaged의 계수는 어떻게 변했는가?</li>
<li>전체 모델의 설명력이 증가했는가? (R^2 값 확인)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>reg_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(avgverb <span class="sc">~</span> classize <span class="sc">+</span> disadvantaged <span class="sc">+</span> school_enrollment <span class="sc">+</span> female <span class="sc">+</span> religious, grades)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>reg_full</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = avgverb ~ classize + disadvantaged + school_enrollment + 
##     female + religious, data = grades)
## 
## Coefficients:
##       (Intercept)           classize      disadvantaged  school_enrollment  
##        78.5607253          0.0033208         -0.3893330          0.0007583  
##            female          religious  
##         0.9237105          2.8761467</code></pre>
</div>
</div>
</section>
<section id="task-2" class="level2">
<h2 class="anchored" data-anchor-id="task-2">Task 2</h2>
<ol type="1">
<li><strong>STAR 데이터</strong>를 다운로드 <a href="https://chung-jiwoong.github.io/FMB819-Slides/chapter_causality/data/star_data.csv">링크</a>. <code>read.csv()</code>를 사용하여 <code>star_df</code> 객체에 저장. <code>NA</code> 값이 있는 행을 제거: <code>star_df &lt;- star_df[complete.cases(star_df),]</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>star_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://chung-jiwoong.github.io/FMB819-Slides/chapter_causality/data/star_data.csv"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>star_df <span class="ot">&lt;-</span> star_df[<span class="fu">complete.cases</span>(star_df),]</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>star_df_2 <span class="ot">&lt;-</span> star_df <span class="sc">%&gt;%</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(grade <span class="sc">==</span> <span class="st">"2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>세 개의 더미 변수를 생성 (<em>힌트</em>: <code>dummy = (variable=="value")</code>):</li>
</ol>
<ul>
<li><code>small</code>: 학생이 소규모 학급에 배정되었으면 TRUE, 아니면 FALSE</li>
<li><code>regular</code>: 학생이 일반 학급에 배정되었으면 TRUE, 아니면 FALSE</li>
<li><code>regular_plus</code>: 학생이 보조 교사가 있는 일반 학급에 배정되었으면 TRUE, 아니면 FALSE</li>
<li>또한, sum 변수를 만들어 위 세 개 변수의 합을 확인. 무엇을 뜻하는가?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>star_df_2 <span class="ot">&lt;-</span> star_df_2 <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">small =</span> (star <span class="sc">==</span> <span class="st">"small"</span>),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">regular =</span> (star <span class="sc">==</span> <span class="st">"regular"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">regular_plus =</span> (star <span class="sc">==</span> <span class="st">"regular+aide"</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">sum =</span> small <span class="sc">+</span> regular <span class="sc">+</span> regular_plus)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>star_df_2 <span class="sc">%&gt;%</span> <span class="fu">count</span>(sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##   sum    n
## 1   1 5672</code></pre>
</div>
</div>
<p>** <code>sum</code> 변수는 항상 1입니다. 이는 <code>small</code>, <code>regular</code>, <code>regular_plus</code> 세 변수는 완전히 공선형(collinear)이라는 의미입니다. 즉, 서로 선형 결합으로 표현할 수 있습니다. 예: <code>small = 1 - (regular + regular_plus)</code> **</p>
<ol start="3" type="1">
<li><code>math</code>를 <code>regular_plus</code>로 회귀 분석. regular+aide 반에 있는 학생의 평균 <code>math</code> 점수는?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>reg_small <span class="ot">&lt;-</span> <span class="fu">lm</span>(math <span class="sc">~</span> small, star_df_2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>reg_small</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ small, data = star_df_2)
## 
## Coefficients:
## (Intercept)    smallTRUE  
##     579.074        7.564</code></pre>
</div>
</div>
<p>**회귀 변수인 small이 더미 변수인 경우, 절편은 FALSE 그룹의 평균이며 계수는 TRUE와 FALSE 그룹 간 평균 차이를 의미합니다. 이 경우, 작은 학급이 아닌 학생들의 예상 수학 점수는 약 579.07이고, 작은 학급에 속한 학생들과의 차이는 7.56점입니다. 따라서 작은 학급 학생의 예상 점수는 579.07 + 7.56 = 586.64 입니다.</p>
<p>수학적으로는 다음과 같습니다:** <span class="math display">\[
\mathbb{E}(\text{math score } | \text{ small} = 0) = b_0 + b_1 \times 0 = b_0 \approx 579.07 \\
\mathbb{E}(\text{math score } | \text{ small} = 1) = b_0 + b_1 \times 1 = b_0 + b_1 \approx 586.64
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>reg_regular <span class="ot">&lt;-</span> <span class="fu">lm</span>(math <span class="sc">~</span> regular, star_df_2)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>reg_regular</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ regular, data = star_df_2)
## 
## Coefficients:
## (Intercept)  regularTRUE  
##     583.231       -5.535</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>reg_plus <span class="ot">&lt;-</span> <span class="fu">lm</span>(math <span class="sc">~</span> regular_plus, star_df_2)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>reg_plus</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ regular_plus, data = star_df_2)
## 
## Coefficients:
##      (Intercept)  regular_plusTRUE  
##          581.859            -1.466</code></pre>
</div>
</div>
<p><strong>다음이 성립함:</strong> <span class="math display">\[
\mathbb{E}(\text{math score } | \text{ regular} = 0) = b_0 + b_1 \times 0 = b_0 \approx 583.23 \\
\mathbb{E}(\text{math score } | \text{ regular} = 1) = b_0 + b_1 \times 1 = b_0 + b_1 \approx 577.7 \\
\mathbb{E}(\text{math score } | \text{ regular+aide} = 0) = b_0 + b_1 \times 0 = b_0 \approx 581.86 \\
\mathbb{E}(\text{math score } | \text{ regular+aide} = 1) = b_0 + b_1 \times 1 = b_0 + b_1 \approx 580.39
\]</span></p>
<ol start="4" type="1">
<li><code>math</code>를 <code>small</code>, <code>regular</code>, <code>regular_plus</code>로 회귀 분석. 어느 범주가 사라졌나?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>reg_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(math <span class="sc">~</span> small <span class="sc">+</span> regular <span class="sc">+</span> regular_plus, star_df_2)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>reg_full</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ small + regular + regular_plus, data = star_df_2)
## 
## Coefficients:
##      (Intercept)         smallTRUE       regularTRUE  regular_plusTRUE  
##          580.393             6.246            -2.696                NA</code></pre>
</div>
</div>
<p><strong><code>regular_plus</code> 변수가 자동으로 제외됩니다. 이는 <code>small</code>, <code>regular</code>, <code>regular_plus</code> 사이에 완전한 선형 종속성이 있기 때문입니다. 기준 범주는 <code>regular+aide</code>이며, 다른 계수들은 이 그룹을 기준으로 해석됩니다. 즉, 작은 학급 학생은 <code>regular+aide</code> 그룹보다 평균 6.25점 높고, 일반 학급 학생은 2.7점 낮습니다.</strong></p>
<p><span class="math display">\[\begin{align}
b_0 &amp;= \mathbb{E}(\text{math score } | \text{ small} = 0 \text{ &amp; } \text{ regular} = 0) \\
&amp;= \mathbb{E}(\text{math score } | \text{ regular + aide} = 1) \\
&amp;\approx 580.39
\end{align}\]</span></p>
<p>이 결과를 이전 질문의 답과 비교해 보면, 정확히 같은 결과를 얻는다는 것을 알 수 있습니다.</p>
<p>같은 방식으로, 우리는 다음과 같은 결론에 도달합니다:</p>
<p><span class="math display">\[\begin{align}
b_1 &amp;= \mathbb{E}(\text{math score } | \text{ small} = 1 \text{ &amp; } \text{ regular} \in \{0,1\}) - \mathbb{E}(\text{math score } | \text{ small} = 0 \text{ &amp; } \text{ regular} \in \{0,1\}) \\
&amp;= b_0 + b_1 \times 1 + b_2 \times \text{regular} - (b_0 + b_1 \times 0 + b_2 \times \text{regular}) \\
&amp;\approx 6.25
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
b_2 &amp;= \mathbb{E}(\text{math score } | \text{ small} \in \{0,1\} \text{ &amp; } \text{ regular} = 1) - \mathbb{E}(\text{math score } | \text{ small} \in \{0,1\} \text{ &amp; } \text{ regular} = 0) \\
&amp;= b_0 + b_1 \times \text{small} + b_2 \times 1 - (b_0 + b_1 \times \text{small} + b_2 \times 0) \\
&amp;\approx -2.7
\end{align}\]</span></p>
<p>쉽게 말하면, 해석은 다음과 같습니다: <code>regular+aide</code> 그룹을 기준으로 할 때, 작은 학급에 속한 학생들은 수학 시험에서 평균 6.25점 더 높은 점수를 받고, 일반 학급에 속한 학생들은 평균 2.7점 더 낮은 점수를 받습니다.</p>
<ol start="5" type="1">
<li><code>math</code>를 <code>star</code> 변수로 회귀 분석. 어느 범주가 사라졌나? 계수를 해석하시오.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(math <span class="sc">~</span> star, star_df_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ star, data = star_df_2)
## 
## Coefficients:
##      (Intercept)  starregular+aide         starsmall  
##          577.696             2.696             8.942</code></pre>
</div>
</div>
<p><strong><code>R</code>은 실제로 범주형 변수에 대해 자동으로 더미 변수를 생성해 주기 때문에, 위에서 각 범주별로 일일이 더미 변수를 만드는 번거로운 작업을 할 필요가 없습니다! 기준(생략) 범주는 <code>regular</code>이므로, 회귀 계수들은 모두 <code>regular</code> 학급 학생들을 기준으로 한 평균 수학 점수의 차이로 해석해야 합니다.</strong></p>
</section>
<section id="task-3" class="level2">
<h2 class="anchored" data-anchor-id="task-3">Task 3</h2>
<ol type="1">
<li>Task 2에서 필터링한 <em>STAR</em> 데이터를 사용하여 <code>math</code>를 <code>school</code> 변수에 대해 회귀 분석하시오. <code>school</code> 변수가 포함하는 값들을 먼저 확인. 회귀 계수를 해석하시오. 누락된 범주 (category)는? 결과가 예상과 일치하는가? 만약 다르다면 왜 그런가? 누락된 변수가 존재할 가능성이 있는가?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>star_df_2 <span class="sc">%&gt;%</span> <span class="fu">count</span>(school)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##       school    n
## 1 inner-city 1199
## 2      rural 2665
## 3   suburban 1476
## 4      urban  332</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(math <span class="sc">~</span> school, star_df_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ school, data = star_df_2)
## 
## Coefficients:
##    (Intercept)     schoolrural  schoolsuburban     schoolurban  
##         561.56           30.18           16.93           20.33</code></pre>
</div>
</div>
<p><strong><code>school</code> 변수는 학교의 위치 유형을 나타내는 범주형 변수입니다. 네 가지 범주가 있으며, 각각은 inner-city(도심), suburban(교외), rural(농촌), urban(도시)입니다.</strong></p>
<p><strong>회귀 분석에서 생략된 기준 범주는 <code>inner-city</code>이므로, 절편은 inner-city에 위치한 학교 학생들의 평균 수학 점수를 나타냅니다. 나머지 계수들은 모두 inner-city 학생들의 예상 점수를 기준으로 해석해야 합니다. 예를 들어, 농촌 학교 학생들은 평균적으로 inner-city 학교 학생들보다 30점 더 높고, 교외 지역 학생들은 약 17점, 도시 지역 학생들은 약 20점 더 높습니다. 일반적으로 inner-city 지역은 저소득층 비율이 높기 때문에, 다른 지역에 비해 점수가 낮은 것이 그로 인해 설명될 수 있습니다. 생략된 변수는 학생 개인 혹은 학교 차원의 불리함을 나타내는 변수일 수 있습니다.</strong></p>
<ol start="2" type="1">
<li><code>lunch</code> 변수가 <code>"free"</code>인 학생들의 비율을 <strong>학교 위치(school) 별로 계산</strong>하시오. 결과를 보고, <strong>무료 점심 자격 여부(<code>free</code>) 변수를 추가하여 이전 회귀 분석을 다시 수행</strong>하시오. <code>free</code> 변수를 추가했을 때 회귀 계수는 어떻게 변화하는가?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>star_df_2 <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(school) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">mean</span>(lunch <span class="sc">==</span> <span class="st">"free"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 4 × 2
##   school     `mean(lunch == "free")`
##   &lt;chr&gt;                        &lt;dbl&gt;
## 1 inner-city                   0.897
## 2 rural                        0.389
## 3 suburban                     0.335
## 4 urban                        0.443</code></pre>
</div>
</div>
<p><strong>예상한 대로, 무료 급식 자격을 갖춘 학생들의 비율(이는 일반적으로 불리함을 나타내는 지표로 사용됨)은 inner-city 학교에서 현저히 높습니다 (해당 학생 비율이 거의 90%에 달함). 반면, 다른 지역에서는 그 비율이 34%에서 44% 사이로 나타납니다.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(math <span class="sc">~</span> school <span class="sc">+</span> lunch, star_df_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ school + lunch, data = star_df_2)
## 
## Coefficients:
##    (Intercept)     schoolrural  schoolsuburban     schoolurban   lunchnon-free  
##        559.228          18.750           4.289          10.114          22.517</code></pre>
</div>
</div>
<p><strong>학생들의 무료 급식 자격 여부를 회귀에 포함하면, rural, suburban, urban 지역에 대한 계수들이 크게 감소하는 것을 확인할 수 있습니다. 이는 학교 위치를 통제한 상태에서도, 무료 급식 자격이 없는 학생들이 평균적으로 자격이 있는 학생들보다 수학 점수가 유의미하게 더 높다는 것을 보여줍니다.</strong></p>
<ol start="3" type="1">
<li><code>math</code>를 <code>star</code> 변수에 대해 회귀 분석하시오. 다음의 모든 변수를 포함하여 다중 회귀 분석을 수행하시오:<br>
<code>math ~ star + gender + ethnicity + lunch + degree + experience + school</code>. 무작위 실험이 <strong>잘 수행되었다고 판단할 수 있는가?</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(math <span class="sc">~</span> gender <span class="sc">+</span> experience, star_df_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ gender + experience, data = star_df_2)
## 
## Coefficients:
## (Intercept)   gendermale   experience  
##   581.35255     -0.91383      0.03453</code></pre>
</div>
</div>
<p><strong>절편 계수는 교사의 경력을 일정하게 유지했을 때 여학생들의 평균 수학 점수를 나타냅니다. 숫자형 변수와 더미 변수를 모두 독립 변수로 포함하고 있기 때문에, 절편은 생략된 범주(이 경우 여성)에 해당하는 회귀선의 절편으로 해석할 수 있습니다.</strong></p>
<p><strong>성별(gender)에 대한 계수는, 교사의 경력이 일정할 때 남학생과 여학생 간 수학 점수의 기대 차이를 나타냅니다. 이 계수는 음수이지만 크기가 작으며, 이는 교사의 경력이 동일할 때 평균적으로 남학생이 여학생보다 약간 낮은 점수를 받는다는 것을 의미합니다. 시각적으로 표현하면, 남학생의 회귀선이 여학생의 회귀선보다 아래에 위치한다는 뜻입니다.</strong></p>
<p><strong>경력(experience)에 대한 계수는 교사의 경력이 1년 늘어날 때 평균적으로 수학 점수가 얼마나 변화하는지를 보여줍니다(성별을 통제한 상태에서). 평균적으로 교사의 경력이 1년 증가할 때 수학 점수는 0.03점 증가합니다. 이는 매우 미미한 효과로, 점수가 3점 오르기 위해서는 100년의 경력 증가가 필요하다는 의미입니다.</strong></p>
<ol start="4" type="1">
<li><strong>다중 회귀 분석</strong>에서 얻은 <strong>수정된</strong> <span class="math inline">\(R^2\)</span> 값을 확인하시오. 수정된 <span class="math inline">\(R^2\)</span> 값이 의미하는 바는 무엇인가? 관측 가능한 개별 학생, 교사, 학교 특성이 학업 성취도에 미치는 중요성에 대해 어떤 결론을 내릴 수 있는가?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(math <span class="sc">~</span> star, star_df_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ star, data = star_df_2)
## 
## Coefficients:
##      (Intercept)  starregular+aide         starsmall  
##          577.696             2.696             8.942</code></pre>
</div>
</div>
<p><strong>계수의 해석은 일반적인 조건부 평균 간의 비교입니다. 즉, 작은 학급에 속한 학생들은 일반 학급(생략된 기준 범주)에 속한 학생들보다 평균적으로 8.94점 더 높은 수학 점수를 받으며, 일반+보조교사 학급에 속한 학생들은 평균적으로 2.70점 더 높게 나타납니다.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>reg_all <span class="ot">&lt;-</span> <span class="fu">lm</span>(math <span class="sc">~</span> star <span class="sc">+</span> gender <span class="sc">+</span> ethnicity <span class="sc">+</span> lunch <span class="sc">+</span> degree <span class="sc">+</span> experience <span class="sc">+</span> school, star_df_2)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>reg_all</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ star + gender + ethnicity + lunch + degree + 
##     experience + school, data = star_df_2)
## 
## Coefficients:
##       (Intercept)   starregular+aide          starsmall         gendermale  
##         557.64898            2.01899            7.89579           -1.07263  
## ethnicityamindian     ethnicityasian      ethnicitycauc  ethnicityhispanic  
##         -21.91483           42.16429           18.61906           15.04510  
##    ethnicityother      lunchnon-free       degreemaster          degreephd  
##          54.67051           18.40555           -1.29047            0.97823  
##  degreespecialist         experience        schoolrural     schoolsuburban  
##          12.11634           -0.05146            3.99491           -4.65503  
##       schoolurban  
##          -3.97039</code></pre>
</div>
</div>
<p><strong>처치 변수 <code>star</code>에 대한 계수는 이전의 단순 회귀에 비해 아주 약간만 감소합니다. 이는 무작위 실험(randomized experiment)이었기 때문에 예상 가능한 결과이며, 무작위 배정이 잘 이루어졌다고 볼 수 있습니다. 만약 무작위 배정이 제대로 되지 않았다면, 다른 변수들을 통제했을 때 <code>star</code>의 계수가 더 크게 변했을 것입니다.</strong></p>
<ol start="5" type="1">
<li>(Optional) <code>math</code>를 <code>gender</code>와 <code>experience</code> 변수에 대해 회귀 분석하시오. 회귀 계수를 어떻게 해석할 수 있는가? 이러한 회귀 분석 결과를 시각적으로 표현한다면 어떻게 보일 것인가?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg_all)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Call:
## lm(formula = math ~ star + gender + ethnicity + lunch + degree + 
##     experience + school, data = star_df_2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -137.882  -27.033   -1.892   25.174  144.834 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       557.64898    1.68995 329.979  &lt; 2e-16 ***
## starregular+aide    2.01899    1.30760   1.544 0.122635    
## starsmall           7.89579    1.36425   5.788 7.52e-09 ***
## gendermale         -1.07263    1.08674  -0.987 0.323675    
## ethnicityamindian -21.91483   28.97355  -0.756 0.449457    
## ethnicityasian     42.16429   11.90591   3.541 0.000401 ***
## ethnicitycauc      18.61906    1.76609  10.543  &lt; 2e-16 ***
## ethnicityhispanic  15.04510   14.53924   1.035 0.300810    
## ethnicityother     54.67051   13.71246   3.987 6.78e-05 ***
## lunchnon-free      18.40555    1.25646  14.649  &lt; 2e-16 ***
## degreemaster       -1.29047    1.17370  -1.099 0.271603    
## degreephd           0.97823    7.08286   0.138 0.890157    
## degreespecialist   12.11634    5.50130   2.202 0.027674 *  
## experience         -0.05146    0.06398  -0.804 0.421259    
## schoolrural         3.99491    2.09764   1.904 0.056898 .  
## schoolsuburban     -4.65503    1.90889  -2.439 0.014775 *  
## schoolurban        -3.97039    2.91817  -1.361 0.173703    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 40.86 on 5655 degrees of freedom
## Multiple R-squared:  0.1489, Adjusted R-squared:  0.1465 
## F-statistic: 61.85 on 16 and 5655 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>이전 회귀의 조정된 <span class="math inline">\(R^2\)</span> 값은 약 0.15로, 이는 해당 모형이 학생들의 수학 점수 변동 중 약 15%만 설명한다는 것을 의미합니다. 다시 말해, 전체 점수 변동의 85%는 설명되지 않은 상태로 남아 있습니다. 쉽게 말하면, 학급 규모, 성별, 인종, 무료 급식 여부, 교사 경력 및 학위, 학교 위치 등은 이 데이터에서 학생들의 수학 점수 차이를 설명하는 데 큰 역할을 하지 못한다는 뜻입니다. 이를 조금 확대 해석하면, 교육 성과의 대부분은 이러한 관측 가능한 변수들로 설명되지 않는다는 주장도 가능합니다. 다만, </strong>이것이 해당 변수들이 교육 성과에 중요한 인과적 효과를 갖지 않는다는 뜻은 절대 아닙니다.**</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>